name: GitHub Action MyRPG
run-name: ${{ github.actor }} is ${{ github.event_name }}ing on the ${{ github.ref_name }} branch ✘

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'ga-i/*'
  pull_request:
    branches-ignore:
      - 'ga-i/*'

env:
  MIRROR_REPO: EpitechPromo2028/B-MUL-200-PAR-2-1-myrpg-paul.colagrande
  MAX_SIZE: 30000
  EXECUTABLE: my_rpg
  FIRST_NAME: Vierre33
  FIRST_AT: '509795682618703874'
  SECOND_NAME: AxiomePro
  SECOND_AT: '365885753730924555'
  THIRD_NAME: BjrTom
  THIRD_AT: '409776240753508375'
  FOURTH_NAME: ncr-t
  FOURTH_AT: '441612891548942337'
  FIFTH_NAME: NULL
  FIFTH_AT: NULL
  CUSTOM_IMAGE: https://cdn.discordapp.com/attachments/1173625780186652702/1230601113816797216/robot-removebg-preview.png?ex=6633e998&is=66217498&hm=2cbe28799df3572c954c540d326d1d30f018bb5db833e643adea75786beeef9a&
# ssh key to set as scret: GIT_SSH_PRIVATE_KEY
# webhhok link to set as scret: DISCORD_WEBHOOK
jobs:
  check_commit:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner != 'EpitechPromo2028' }}
    steps:
      - uses: actions/checkout@v4
      - run: echo -ne "**Commit** standart not respected ! " > failed_task.txt
      - uses: actions/upload-artifact@v2
        with:
          name: failed_task
          path: failed_task.txt
      - uses: webiny/action-conventional-commits@v1.2.0
      - run: echo -ne "" > failed_task.txt
      - uses: actions/upload-artifact@v2
        with:
          name: failed_task
          path: failed_task.txt

  check_repository_size:
    needs: check_commit
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    env:
      EXIT: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: failed_task
      - name: Check size
        run: |
          SIZE=$(du -s --exclude=.git | awk '{print $1}')
          if [ $SIZE -gt $MAX_SIZE ]; then
            echo "::error title=Repo size over $MAX_SIZE"B" !::🚫 Actual: $SIZE"B""
            echo -ne "Repository **size** excess ! " >> failed_task.txt
            echo "EXIT=true" >> $GITHUB_ENV
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: failed_task
          path: failed_task.txt
      - run: if [ $EXIT == true ]; then exit 1; fi

  check_coding_style:
    needs: check_commit
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    env:
      EXIT: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: failed_task
      - name: Coding style
        run: check.sh $(pwd) $(pwd)
      - name: Display coding style errors
        run: |
          NB_ERRORS=$(cat coding-style-reports.log | wc -l)
          if [ $NB_ERRORS -ge 1 ]; then
            while IFS= read -r line
              do
                FILE=$(echo $line | cut -d ':' -f 1)
                LINE=$(echo $line | cut -d ':' -f 2)
                TYPE=$(echo $line | cut -d ':' -f 3)
                ERROR=$(echo $line | cut -d ':' -f 4)
              echo "::error file=$FILE,line=$LINE,title=$ERROR coding style error::❌ $TYPE"
            done < coding-style-reports.log
              echo "::error title=Coding style errors !::🚫 $NB_ERRORS errors"
              echo -ne "Coding **style** errors ! " >> failed_task.txt
              echo "EXIT=true" >> $GITHUB_ENV
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: failed_task
          path: failed_task.txt
      - run: if [ $EXIT == true ]; then exit 1; fi

  check_compilation:
    needs: check_commit
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    env:
      EXIT: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: failed_task
      - name: Compilation
        timeout-minutes: 2
        run: make
      - name: Clear .o
        run: make clean
      - name: Check executables
        run: |
          if [ ! -x $EXECUTABLE ]; then
            echo "::error title=Compilation error !::🚫 $EXECUTABLE not executable"
            echo -ne "Program not **compiling** ! " >> failed_task.txt
            echo "EXIT=true" >> $GITHUB_ENV
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: failed_task
          path: failed_task.txt
      - run: if [ $EXIT == true ]; then exit 1; fi

  push_to_mirror:
    needs: [ check_repository_size, check_coding_style, check_compilation ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:${{ env.MIRROR_REPO }}.git
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}

  webhook_request_done:
    runs-on: ubuntu-latest
    needs: push_to_mirror
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
      - name: Send a request to webhook
        run: |
          HASH=$(git rev-parse --short "$GITHUB_SHA")
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
            "username": "${{ github.event.head_commit.message }}",
            "content": "",
            "embeds": [{
                "type": "rich",
                "description": "${{ github.event_name }}ed on **${{ github.ref_name }}**",
                "color": 65280,
                "author": {
                  "name": "${{ github.actor }}",
                  "url": "https://github.com/${{ github.actor }}",
                  "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
                },
                "footer": {
                  "text": "commit hash: '$HASH'"
                }
            }]
            }' ${{ secrets.DISCORD_WEBHOOK }})
            echo "Webhook server response: $RESPONSE"

  webhook_request_failed:
    runs-on: ubuntu-latest
    needs: push_to_mirror
    if: ${{ failure() }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: failed_task
      - name: Choose mention
        run: |
          if [ ${{ github.actor }} == $FIRST_NAME ]; then
            MENTION="<@$FIRST_AT>"
          elif [ ${{ github.actor }} == $SECOND_NAME ]; then
            MENTION="<@$SECOND_AT>"
          elif [ ${{ github.actor }} == $THIRD_NAME ]; then
            MENTION="<@$THIRD_AT>"
          elif [ ${{ github.actor }} == $FOURTH_NAME ]; then
            MENTION="<@$FOURTH_AT>"
          elif [ ${{ github.actor }} == $FIFTH_NAME ]; then
            MENTION="<@$FIFTH_AT>"
          else
            MENTION=@everyone
          fi
          echo "MENTION=$MENTION" >> $GITHUB_ENV
      - name: Send a request to webhook
        run: |
          echo -ne "\n" >> failed_task.txt
          FAILED_TASK=$(cat failed_task.txt)
          HASH=$(git rev-parse --short "$GITHUB_SHA")
          RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
            "username": "${{ github.event.head_commit.message }}",
            "content": "'$MENTION'",
            "embeds":
            [
              {
                "type": "rich",
                "title": "'"$FAILED_TASK"'",
                "description": "failed to ${{ github.event_name }} on **${{ github.ref_name }}**",
                "color": 16711680,
                "thumbnail": {
                  "url": "'$CUSTOM_IMAGE'"
                },
                "footer": {
                  "text": "commit hash: '$HASH'"
                },
                "author": {
                  "name": "${{ github.actor }}",
                  "url": "https://github.com/${{ github.actor }}",
                  "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
                },
                "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            ]
            }' ${{ secrets.DISCORD_WEBHOOK }})
            echo "Webhook server response: $RESPONSE"
